services:
  web:
    image: php:7.4-apache
    build: 
      context: ./docker
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: php_cliente_crud_db